services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - quick-app-net

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - quick-app-net

networks:
  quick-app-net:
    driver: bridge
