frontend:
  image:
    repository: meravisingh/frontend
    tag: 74e3f30
    pullPolicy: IfNotPresent

backend:
  image:
    repository: meravisingh/backend
    tag: 74e3f30
    pullPolicy: IfNotPresent
