frontend:
  image:
    repository: meravisingh/frontend
    tag: 66cfd0b
    pullPolicy: IfNotPresent

backend:
  image:
    repository: meravisingh/backend
    tag: 66cfd0b
    pullPolicy: IfNotPresent
